import React from 'react';
import './TermsPage.css';

function TermsPage({ onAccept }) {
  return (
    <div className="terms-container content-animated">
      <h1>Terms & Conditions</h1>
      <div className="terms-content">
        <p>Welcome to NSE Stock Predictor. This tool is for educational and informational purposes only and does not constitute financial advice.</p>
        <p>The predictions generated by the LSTM model are based on historical data and technical indicators. They are not guaranteed to be accurate. The stock market is volatile, and past performance is not indicative of future results.</p>
        <p>By using this application, you agree that you are solely responsible for any investment decisions you make. The creators of this tool are not liable for any financial losses you may incur.</p>
        <p>Please consult with a qualified financial advisor before making any investment decisions. Do not invest more than you are willing to lose.</p>
      </div>
      <button onClick={onAccept} className="terms-accept-button">
        I Read & Accept
      </button>
    </div>
  );
}

export default TermsPage;